export const robot =[
    {
        id:1,
        name:"Subashini",
        user:"Suba",
        email:"Subashini@gmail.com",
    },
    {
        id:2,
        name:"Afzal",
        user:"afzal",
        email:"afzal@gmail.com",
    },
    {
        id:3,
        name:"Preethi",
        user:"Preethi",
        email:"Preethi@gmail.com",
    },
    {
        id:4,
        name:"Jeo",
        user:"Jeo",
        email:"Jeo@gmail.com",
    },
    {
        id:5,
        name:"Ajay",
        user:"Ajay",
        email:"Ajay@gmail.com",
    },
    {
        id:6,
        name:"Yalu",
        user:"Yalu",
        email:"Yalu@gmail.com",
    },
    {
        id:7,
        name:"Theeran",
        user:"Theeran",
        email:"Theeran@gmail.com",
    },
    {
        id:8,
        name:"Jessy",
        user:"Jessy",
        email:"Jessy@gmail.com",
    },
    {
        id:9,
        name:"Maha",
        user:"Maha",
        email:"Maha@gmail.com",
    },
    {
        id:10,
        name:"Rose",
        user:"Rose",
        email:"Rose@gmail.com",
    },
    {
        id:11,
        name:"Jack",
        user:"Jack",
        email:"Jack@gmail.com",
    },
    {
        id:12,
        name:"Jerry",
        user:"Jerry",
        email:"Jerry@gmail.com",
    },

]
    
